### ISSUE TITLE
Document how to pass the args

### ISSUE THREAD

**Issue by alainpannetier** [lucaswerkmeister/pygments-server#1]
Thanks for sharing this development.

Took me a while to understand how to pass the arguments to flask.
One just needs to string "args" arguments. As many as needed.
Might be useful to add this to the doc.

http://192.168.2.2:7879/?args=-l&args=python&args=-f&args=html&args=-O&args=style=native,full=True

**Comment by lucaswerkmeister** [comment]
Why do you want to know how to pass arguments to flask? You’re expected to use the `pygmentize` script which takes care of that for you.

**Comment by alainpannetier** [comment]
I probably don't understand your response.

1/ I'm using your server because my objective is to interact with pygmentize through http (REST API style).
    I assume this is why you (and Khan) wrapped pygmentize in a server in the first place.

2/ In this configuration, I shall need to submit different code snippets, in different languages (possibly different styles, and formatters). For instance:
    In blog page 1, I will format some python
    In blog page 2, I will format some lua, and R. Etc.

3/ I assume this is why you state "it supports all pygmentize options".

Therefore, in my blog server (acting as a http flask client), I need to know how to pass arguments to flask (your pygments-server).

Did I miss something?

**Comment by lucaswerkmeister** [comment]
No, I wouldn’t say my objective is to interact with pygmentize through HTTP, at least not directly. My objective is to have a working `pygmentize` program, because I have existing upstream software which targets the `pygmentize` CLI (MediaWiki’s [SyntaxHighlight extension](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:SyntaxHighlight)). Using a server, and talking to it over HTTP, is from this perspective just one possible way to implement a `pygmentize` program – next to the most obvious option, of course, which is to just use the regular `pygmentize`. My motivation for using a server is that I have to call `pygmentize` from an environment where Python 3 isn’t installed, so HTTP communication is one way to make the syntax highlighting happen in a different environment where Python 3 is available. For the Khan folks, my understanding is that the objective is the same (their software using `pygmentize` is Phabricator), but the motivation is different: [their README](https://github.com/Khan/pygments-server#readme) makes it sound like they mainly want to eliminate the Python startup cost.

If what we really need is a `pygmentize` program, then the HTTP server is just one half of the solution: the other half is the shell script talking to the server. And the interface between the shell script and the server can be considered internal, which is why I’m hesitant to document it. If I change the HTTP interface, and adapt the script at the same time, should that be considered a breaking change?

**Comment by alainpannetier** [comment]
" the other half is the shell script talking to the server. "
You would be right if you'd also include the caller script here (from your mediawiki I guess).
In which case the http API could be considered internal. But here you're sharing some http server (through Flask).

Anyway. I have no time to lose arguing with you.
Hopefully, some other hypothetical user of your hack will find this useful.
Otherwise feel free to close and even delete.
As for me, I move on. Cheers.

**Comment by lucaswerkmeister** [comment]
I don’t understand what you mean – the caller script is [here](https://github.com/lucaswerkmeister/pygments-server/blob/main/pygmentize)?

**Comment by lucaswerkmeister** [comment]
:shrug:
